/******************************************************************************
 * nvmparams.h
 *
 * Non-volatile memory parameter management -- vendored module, public header.
 *
 * This is the ONLY header an application needs to include. It pulls in your
 * nvmparams_config.h for you; do not include that file directly.
 *
 * The module is hardware-independent: it contains no storage drivers. The
 * application supplies read and write functions as pointers in
 * nvm_pool_config_t. See README.md for adoption instructions, driver-writing
 * guidance and the linker-script recipe for an internal-flash pool.
 *
 * DO NOT EDIT THIS FILE when adopting. Everything intended to be adjusted
 * lives in nvmparams_config.h.
 ******************************************************************************/

#ifndef NVMPARAMS_H
#define NVMPARAMS_H

#include <stdint.h>
#include <stdbool.h>

/*=============================================================================
 * PART A -- definitions the adopter's configuration header needs.
 *
 * Anything referenced from nvmparams_config.h must appear ABOVE the include
 * of that file, further down. Everything depending on values the config
 * supplies lives in Part B, below it.
 *===========================================================================*/

/*----------------------------------------------------------------------------
 * Parameter object identifier.
 *
 * Deliberately an explicit uint16_t rather than an enum: this type is the
 * first member of nvm_object_t, which is the ON-MEDIA record layout. A packed
 * enum's width depends on its largest enumerator and on compiler flags, so
 * using one here would let the stored record silently change size. The
 * application declares its own enum of IDs and passes the labels directly --
 * they convert implicitly and need no cast.
 *--------------------------------------------------------------------------*/

typedef uint16_t nvm_param_id_t;

/*----------------------------------------------------------------------------
 * ID space partition.
 *
 *   0x0000            NVM_PARAM_UNUSED -- marks a deleted/free object
 *   0x0001 .. 0xFEFF  the application's, declared in nvmparams_config.h
 *   0xFF00 .. 0xFFFF  reserved to nvmparams
 *
 * The top page is reserved rather than the bottom because NVM_PARAM_END_OF_DATA
 * must be 0xFFFF, so that the end-of-list sentinel coincides with the erased
 * state of NOR flash.
 *
 * Reserved IDs are enforced at runtime: x_nvm_create(), x_nvm_set() and
 * x_nvm_delete() reject them with NVM_ERROR_ID_RESERVED. Reads are permitted,
 * so an application can inspect module-owned objects.
 *
 * NVM_ID_APP_MAX may be raised by an adopter whose legacy IDs already occupy
 * part of the reserved page -- define it before including this header. Doing so
 * forfeits headroom for future module features.
 *--------------------------------------------------------------------------*/

#define NVM_PARAM_UNUSED            ((nvm_param_id_t) 0x0000u)
#define NVM_PARAM_END_OF_DATA       ((nvm_param_id_t) 0xFFFFu)

#define NVM_ID_APP_FIRST            ((nvm_param_id_t) 0x0001u)

#ifndef NVM_ID_APP_MAX
#define NVM_ID_APP_MAX              ((nvm_param_id_t) 0xFEFFu)
#endif

_Static_assert(NVM_ID_APP_MAX <= 0xFFFEu,
               "NVM_ID_APP_MAX must leave 0xFFFF free for NVM_PARAM_END_OF_DATA");

#define NVM_ID_IS_RESERVED(id)      (((id) < NVM_ID_APP_FIRST) || ((id) > NVM_ID_APP_MAX))

/*----------------------------------------------------------------------------
 * Result codes.
 *
 * Negative values are module error codes. Zero is success. POSITIVE VALUES ARE
 * RESERVED FOR DEVICE-SPECIFIC ERRORS returned by a storage driver, and are
 * propagated to the caller unchanged so that, for example, an SPI status code
 * survives to where someone can read it.
 *
 * Callers must therefore test against NVM_ERROR_NONE -- never against a list of
 * known codes, and never "< 0".
 *--------------------------------------------------------------------------*/

typedef int16_t nvm_error_t;

#define NVM_ERROR_NONE              ((nvm_error_t)   0)  /* Success */
#define NVM_ERROR_PARAMETER         ((nvm_error_t)  -1)  /* Invalid parameter or internal state */
#define NVM_ERROR_MEMORY            ((nvm_error_t)  -2)  /* Memory allocation failure */
#define NVM_ERROR_DEVICE            ((nvm_error_t)  -3)  /* Generic device error */
#define NVM_ERROR_ID_NOT_FOUND      ((nvm_error_t)  -4)  /* Requested object ID does not exist */
#define NVM_ERROR_OBJECT_EXISTS     ((nvm_error_t)  -5)  /* Object already present (x_nvm_create; not really an error) */
#define NVM_ERROR_OBJECT_NOT_FOUND  ((nvm_error_t)  -6)  /* Object not found in the pool */
#define NVM_ERROR_POOL_CORRUPT      ((nvm_error_t)  -7)  /* Pool is corrupt or improperly formatted */
#define NVM_ERROR_NO_CHANGE         ((nvm_error_t)  -8)  /* Commit requested, nothing modified (not really an error) */
#define NVM_ERROR_ID_RESERVED       ((nvm_error_t)  -9)  /* Attempted write access to a module-reserved ID */
#define NVM_ERROR_POOL_FORMATTED    ((nvm_error_t) -10)  /* Media was blank; pool formatted. NOTHING WAS LOST */
#define NVM_ERROR_POOL_REFORMATTED  ((nvm_error_t) -11)  /* Media was corrupt; pool reformatted. DATA WAS DESTROYED */

/*----------------------------------------------------------------------------
 * Pool data signature, and the placeholder written into the CRC field when no
 * CRC function is supplied. Both are legacy values; do not change them.
 *--------------------------------------------------------------------------*/

#define NVM_DATA_SIGNATURE          0x5AA5A55Au
#define NVM_CRC_PLACEHOLDER         0xDEADC0DEu

/*=============================================================================
 * The adopter's control panel.
 *===========================================================================*/

#define NVMPARAMS_H_INSIDE
#include "nvmparams_config.h"
#undef NVMPARAMS_H_INSIDE

/*=============================================================================
 * PART B -- everything that depends on configuration values.
 *===========================================================================*/

_Static_assert((NVM_LABEL_MAX_LENGTH % 4) == 0,
               "NVM_LABEL_MAX_LENGTH must be a multiple of 4 to keep the pool "
               "header 32-bit aligned");

/*----------------------------------------------------------------------------
 * Pool header -- ON-MEDIA LAYOUT. Do not reorder or resize.
 *
 * The CRC covers the object data only, not this header.
 *--------------------------------------------------------------------------*/

typedef struct
{
    uint32_t u32_signature;
    uint32_t u32_crc;
    uint32_t u32_write_count;               /* Monotonic. Never reset. */
    char     c_label[NVM_LABEL_MAX_LENGTH]; /* Informational only; not NUL-guaranteed */
}
nvm_header_t;

/*----------------------------------------------------------------------------
 * Object record -- ON-MEDIA LAYOUT. Do not reorder or resize.
 *
 * The data field occupies u16_size rounded up to a multiple of 4 bytes. The
 * pool is a sequential list terminated by a record whose x_id is
 * NVM_PARAM_END_OF_DATA and whose u16_size is 0.
 *--------------------------------------------------------------------------*/

typedef struct
{
    nvm_param_id_t x_id;
    uint16_t       u16_size;    /* Actual object size; need not be a multiple of 4 */
    uint8_t        u8_data[0];
}
nvm_object_t;

/*----------------------------------------------------------------------------
 * Smallest usable pool: header, two 32-bit objects with their overhead, and
 * the end-of-list record. Derived rather than hardcoded, so it tracks
 * NVM_LABEL_MAX_LENGTH automatically.
 *--------------------------------------------------------------------------*/

#define NVM_POOL_SIZE_MIN   ( sizeof(nvm_header_t)                  \
                            + ((sizeof(nvm_object_t) + 4u) * 2u)    \
                            + sizeof(nvm_object_t) )

_Static_assert(NVM_POOL_SIZE_DEFAULT >= NVM_POOL_SIZE_MIN,
               "NVM_POOL_SIZE_DEFAULT is too small to hold a pool header, two "
               "objects and an end-of-list record");

_Static_assert((NVM_POOL_SIZE_DEFAULT % 4) == 0,
               "NVM_POOL_SIZE_DEFAULT must be a multiple of 4");

/*----------------------------------------------------------------------------
 * What a storage driver is given.
 *
 * The driver moves u32_size bytes between p_v_data and ux_address. That is the
 * whole contract:
 *
 *   - The driver validates its own parameters and reports PHYSICAL DEVICE
 *     ACCESS ERRORS ONLY. It performs no integrity checking -- deciding whether
 *     data is valid is this module's job.
 *   - The driver knows nothing about wear levelling. ux_address is the final
 *     effective address, already resolved by the module.
 *   - Return NVM_ERROR_NONE on success. Positive values are yours to define as
 *     device-specific error codes and reach the caller unchanged.
 *
 * ux_address is deliberately an integer, not a pointer: it is a memory address
 * for internal flash, a byte offset for SPI flash, and an lseek()/fseek()
 * offset for a file-backed driver.
 *--------------------------------------------------------------------------*/

typedef struct
{
    uintptr_t   ux_address;     /* Effective device address, module-computed */
    uint32_t    u32_size;       /* Bytes to transfer */
    void       *p_v_data;       /* RAM pool: source for write, destination for read */
    void       *p_v_context;    /* Driver's own; e.g. a file path or bus handle */
}
nvm_media_t;

typedef nvm_error_t (*pfn_nvm_read_t) (const nvm_media_t *p_x_media);
typedef nvm_error_t (*pfn_nvm_write_t)(const nvm_media_t *p_x_media);
typedef uint32_t    (*pfn_nvm_crc_t)  (const void *p_v_data, uint32_t u32_size);

/*----------------------------------------------------------------------------
 * What x_nvm_pool_init() does when the media does not hold a valid pool.
 *
 * A driver that returns an error is a fourth case, distinct from all of these:
 * the module then knows nothing about the contents and ALWAYS aborts, under
 * every policy. Writing to a device you could not read is how a transient fault
 * becomes permanent data loss.
 *--------------------------------------------------------------------------*/

typedef enum
{
    /* Format blank media; abort on corrupt. The safe default. */
    NVM_INIT_FORMAT_IF_BLANK = 0,

    /* Format blank media; reformat corrupt media, destroying its contents.
     * Reported as NVM_ERROR_POOL_REFORMATTED. */
    NVM_INIT_FORMAT_IF_INVALID,

    /* Never write. Abort on anything but a valid pool, blank included.
     * For pools that must have been provisioned beforehand -- factory
     * calibration, serial numbers -- where silently manufacturing defaults
     * would hide a production fault. */
    NVM_INIT_REQUIRE_VALID
}
nvm_init_policy_t;

/*----------------------------------------------------------------------------
 * Pool configuration, supplied by the application to x_nvm_pool_init().
 *
 * May be a ROM constant: this module never writes to it, and does not retain
 * the pointer once init returns. It may equally be a stack temporary.
 *
 * EVERY FIELD'S ZERO VALUE IS A SANE DEFAULT, except u32_size, which must be
 * set. Use designated initializers and write only what you need.
 *--------------------------------------------------------------------------*/

typedef struct
{
    const char       *p_c_label;        /* NULL = unlabelled */
    pfn_nvm_read_t    pfn_read;         /* NULL = never read; pool starts blank */
    pfn_nvm_write_t   pfn_write;        /* NULL = never persist */
    pfn_nvm_crc_t     pfn_crc;          /* NULL = validate by signature only */
    uintptr_t         ux_base_address;  /* Device address/offset of the pool */
    uint32_t          u32_size;         /* REQUIRED. >= NVM_POOL_SIZE_MIN, multiple of 4 */
    uint32_t          u32_alloc_unit;   /* Device erase/sector size; 0 = "same as pool size" */
    void             *p_v_ram_buffer;   /* NULL = allocate internally, if enabled */
    void             *p_v_context;      /* Passed through to your driver untouched */
    uint8_t           u8_wear_blocks;   /* 0 or 1 = no wear levelling */
    nvm_init_policy_t x_init_policy;    /* 0 = NVM_INIT_FORMAT_IF_BLANK */
}
nvm_pool_config_t;

/*----------------------------------------------------------------------------
 * Pool handle. The application declares one per pool and passes it to
 * x_nvm_pool_init(); it does not initialise the members itself.
 *
 * u8_user1, u16_user2 and u16_commit_timer are the application's to read and
 * write. The rest is module state.
 *--------------------------------------------------------------------------*/

typedef struct
{
    uint8_t         u8_need_commit;     /* Set: content modified, commit needed */
    uint8_t         u8_internal_malloc; /* Set: p_v_data was allocated by init */
    uint8_t         u8_user1;           /* Free for application use */
    uint8_t         u8_wear_blocks;     /* Wear-level block count, 1 = none */
    uint16_t        u16_commit_timer;   /* Auto-commit counter; see the accessors below */
    uint16_t        u16_user2;          /* Free for application use */
    uint32_t        u32_size;           /* Pool size, bytes */
    uint32_t        u32_alloc_unit;     /* Device allocation unit */
    uint32_t        u32_block_stride;   /* Bytes between wear-level blocks */
    uintptr_t       ux_base_address;    /* Device address/offset of block 0 */
    void           *p_v_data;           /* RAM pool */
    pfn_nvm_read_t  pfn_read;
    pfn_nvm_write_t pfn_write;
    pfn_nvm_crc_t   pfn_crc;
    nvm_media_t     x_media;            /* Restamped before each driver call */
    nvm_init_policy_t x_init_policy;
}
nvm_pool_t;

/*=============================================================================
 * Public API
 *===========================================================================*/

/* Pool lifecycle. */
extern nvm_error_t x_nvm_pool_init(nvm_pool_t *p_x_pool, const nvm_pool_config_t *p_x_config);
extern nvm_error_t x_nvm_pool_release(nvm_pool_t *p_x_pool);

/* Object access. The write-side calls reject module-reserved IDs; x_nvm_get()
 * and x_nvm_get_size() do not, so the application retains read visibility. */
extern nvm_error_t x_nvm_create(nvm_pool_t *p_x_pool, nvm_param_id_t x_id,
                                uint16_t u16_size, const void *p_v_default);
extern nvm_error_t x_nvm_delete(nvm_pool_t *p_x_pool, nvm_param_id_t x_id);
extern nvm_error_t x_nvm_set(nvm_pool_t *p_x_pool, nvm_param_id_t x_id, const void *p_v_data);
extern nvm_error_t x_nvm_get(nvm_pool_t *p_x_pool, nvm_param_id_t x_id, void *p_v_data);
extern nvm_error_t x_nvm_get_size(nvm_pool_t *p_x_pool, nvm_param_id_t x_id, uint16_t *p_u16_size);

/* Persist all pending changes. Returns NVM_ERROR_NO_CHANGE if there were none. */
extern nvm_error_t x_nvm_commit(nvm_pool_t *p_x_pool);

/*----------------------------------------------------------------------------
 * Auto-commit timer helpers.
 *
 * The module keeps the counter; the POLICY is the application's. Call the tick
 * from a periodic timer, passing the elapsed interval in whatever unit you
 * compare against -- both calls are no-ops while nothing needs committing, so
 * they are safe to call unconditionally.
 *
 * The counter measures time since the LAST change, not the first, so a pool
 * under continuous modification defers indefinitely. That is intentional: it
 * minimises write cycles. Call x_nvm_commit() directly at moments where a
 * commit must happen regardless -- before power-down, for instance.
 *
 * b_nvm_commit_time_elapsed() is level-triggered, not edge-triggered: it stays
 * true until something resets the counter. A successful commit does that.
 *--------------------------------------------------------------------------*/

extern void v_nvm_commit_timer_tick (nvm_pool_t *p_x_pool, uint16_t u16_elapsed);
extern bool b_nvm_commit_time_elapsed(const nvm_pool_t *p_x_pool, uint16_t u16_limit);
extern void v_nvm_commit_timer_reset(nvm_pool_t *p_x_pool);

/*----------------------------------------------------------------------------
 * Direct media access. Not recommended in application code; exposed because
 * pool-erase and diagnostic tooling needs it.
 *--------------------------------------------------------------------------*/

extern nvm_object_t * p_x_nvm_search(nvm_pool_t *p_x_pool, nvm_param_id_t x_id);
extern nvm_object_t * p_x_next_nvm_object(nvm_object_t *p_x_nvm_object);
extern nvm_error_t    x_nvm_read(nvm_pool_t *p_x_pool);
extern nvm_error_t    x_nvm_write(nvm_pool_t *p_x_pool);

#endif /* NVMPARAMS_H */
