/******************************************************************************
 * event_queue.h
 *
 * Variable-length event queue -- vendored module, public header.
 *
 * A ring-buffer FIFO of small records: a 16-bit event ID, a 16-bit payload
 * size, and 0..65535 payload bytes. Producers (including ISRs) push with
 * x_event_queue_put(); a consumer pops with x_event_queue_get() into its own
 * storage. Copy-in/copy-out: the queue never hands out interior pointers.
 *
 * This is the ONLY header an application needs to include. It pulls in your
 * event_queue_config.h for you; do not include that file directly.
 *
 * Thread safety
 * -------------
 * With NULL lock functions the queue is lock-free for ONE producer context and
 * ONE consumer context (SPSC): each side owns its own monotonic counters, the
 * other side only reads them, and aligned 32-bit access is atomic on the
 * Cortex-M targets this module is written for. No interrupt masking occurs.
 *
 * With multiple producer contexts, supply pfn_lock/pfn_unlock in the config.
 * They wrap the PUT PATH ONLY -- their sole job is serializing producers among
 * themselves; the single consumer never takes the lock. The lock must mask
 * every producer context of this queue except the caller's own (on Cortex-M0+
 * that means PRIMASK or per-IRQ NVIC gating; there is no BASEPRI).
 *
 * DO NOT EDIT THIS FILE when adopting. Everything intended to be adjusted
 * lives in event_queue_config.h.
 ******************************************************************************/

#ifndef EVENT_QUEUE_H
#define EVENT_QUEUE_H

#include <stdint.h>
#include <stdbool.h>

/*=============================================================================
 * PART A -- definitions the adopter's configuration header may need.
 *===========================================================================*/

/*----------------------------------------------------------------------------
 * Result codes.
 *
 * Negative values are real errors: the operation did not do what was asked in
 * a way that loses data or indicates misuse. Positive values are information:
 * the operation did something defensible the caller may want to know about.
 * Zero is unqualified success. Callers can therefore triage with
 * "if (x < 0)" and only inspect specific codes when they care.
 *
 * Notably: put-on-full is an ERROR (the event was dropped -- the producer must
 * know), while get-on-empty is a STATUS (nothing was lost; it is the idle
 * result of every polling loop).
 *
 * The packed attribute plus the bounding values force a genuine signed 16-bit
 * type (GCC extension, Clang-compatible), so the enum itself is the compact
 * return type -- no separate int16_t typedef needed.
 *--------------------------------------------------------------------------*/

typedef enum __attribute__((packed))
{
    EQ_ERROR_MIN        = -32768,   /* Bounding value -- forces int16 range */

    EQ_ERROR_PARAMETER  = -1,       /* NULL/invalid argument or lock config */
    EQ_ERROR_NOT_INIT   = -2,       /* Handle never created, or destroyed */
    EQ_ERROR_FULL       = -3,       /* Put: no room; the event was NOT queued */
    EQ_ERROR_MEMORY     = -4,       /* Create: buffer allocation failed */
    EQ_ERROR_ALIGNMENT  = -5,       /* Create: caller buffer not 4-byte aligned */
    EQ_ERROR_SIZE       = -6,       /* Create: size below minimum after round-down */

    EQ_OK               = 0,        /* Success */

    EQ_STATUS_EMPTY     = 1,        /* Get: queue empty; nothing extracted */
    EQ_STATUS_TRUNCATED = 2,        /* Get: event consumed, payload larger than
                                     * the caller's buffer; overflow discarded */
    EQ_STATUS_SIZE_ROUNDED = 3,     /* Create: size was not a multiple of 4 and
                                     * was rounded DOWN; the queue is live */

    EQ_INFO_MAX         = 32767     /* Bounding value -- forces int16 range */
}
event_queue_status_t;

_Static_assert(sizeof(event_queue_status_t) == 2,
               "event_queue_status_t must pack to 16 bits -- is the compiler "
               "honouring __attribute__((packed)) on enums?");

/*----------------------------------------------------------------------------
 * Record header -- the queue's wire format.
 *
 * Every queued record occupies sizeof(event_queue_header_t) + u16_data_size
 * bytes, rounded up to a multiple of 4. u16_data_size always holds the TRUE
 * payload size; the rounding exists only in the space accounting.
 *
 * This struct describes the layout; the implementation never casts it onto
 * ring-buffer memory (records may straddle the wrap point, and Cortex-M0+
 * hard-faults on unaligned access). Headers move through aligned locals.
 *--------------------------------------------------------------------------*/

typedef struct
{
    uint16_t u16_id;            /* Application-defined event identifier */
    uint16_t u16_data_size;     /* TRUE payload size, bytes -- not rounded */
    uint8_t  u8_data[];         /* Payload follows immediately */
}
event_queue_header_t;

/*----------------------------------------------------------------------------
 * Get-side transfer record, caller-filled.
 *
 * Zero-means-default: every member a designated initializer leaves at 0/NULL
 * composes safely. An all-zero record is a valid "consume the event and tell
 * me what it was" request (payload discarded, ID and true size returned).
 *--------------------------------------------------------------------------*/

typedef struct
{
    uint16_t  u16_id;           /* out: event ID */
    uint16_t  u16_data_size;    /* out: TRUE stored payload size, always set */
    uint16_t  u16_buf_size;     /* in:  capacity of pv_data, bytes */
    void     *pv_data;          /* in:  payload destination; NULL = discard */
}
event_queue_record_t;

/*----------------------------------------------------------------------------
 * Producer-serialization lock. See "Thread safety" above. Both pointers must
 * be supplied together or both left NULL.
 *--------------------------------------------------------------------------*/

typedef void (*pfn_event_queue_lock_t)(void);

/*----------------------------------------------------------------------------
 * Queue configuration, supplied by the application to x_event_queue_create().
 *
 * May be a ROM constant: this module never writes to it, and does not retain
 * the pointer once create returns. It may equally be a stack temporary, or
 * NULL for an all-defaults queue.
 *
 * EVERY FIELD'S ZERO VALUE IS A SANE DEFAULT. Use designated initializers and
 * write only what you need.
 *--------------------------------------------------------------------------*/

typedef struct
{
    uint32_t               u32_size;    /* Bytes; 0 = EVENT_QUEUE_DEFAULT_SIZE.
                                         * Rounded DOWN to a multiple of 4
                                         * (EQ_STATUS_SIZE_ROUNDED reports it) */
    void                  *pv_buffer;   /* 4-byte aligned; NULL = allocate
                                         * internally, if enabled */
    pfn_event_queue_lock_t pfn_lock;    /* NULL = no locking (SPSC contract) */
    pfn_event_queue_lock_t pfn_unlock;
}
event_queue_config_t;

/*=============================================================================
 * The adopter's control panel.
 *===========================================================================*/

#define EVENT_QUEUE_H_INSIDE
#include "event_queue_config.h"
#undef EVENT_QUEUE_H_INSIDE

/*=============================================================================
 * PART B -- everything that depends on configuration values.
 *===========================================================================*/

/*----------------------------------------------------------------------------
 * Allocator seam. The adopter's configuration header may define
 * EVENT_QUEUE_MALLOC(size) / EVENT_QUEUE_FREE(ptr) to route internal ring
 * allocation through an alternative allocator (an RTOS heap, a pool
 * allocator); any #includes that alternative needs belong in the config
 * header too. Left undefined, they fall through to the C library.
 * Irrelevant when EVENT_QUEUE_ENABLE_MALLOC is 0.
 *--------------------------------------------------------------------------*/

#ifndef EVENT_QUEUE_MALLOC
#define EVENT_QUEUE_MALLOC(u32_size)    malloc(u32_size)
#endif
#ifndef EVENT_QUEUE_FREE
#define EVENT_QUEUE_FREE(pv)            free(pv)
#endif

/*----------------------------------------------------------------------------
 * Smallest legal queue: two zero-payload records.
 *--------------------------------------------------------------------------*/

#define EVENT_QUEUE_SIZE_MIN    (sizeof(event_queue_header_t) * 2u)

_Static_assert(EVENT_QUEUE_DEFAULT_SIZE >= 8u,
               "EVENT_QUEUE_DEFAULT_SIZE must hold at least two zero-payload "
               "records (EVENT_QUEUE_SIZE_MIN)");

_Static_assert((EVENT_QUEUE_DEFAULT_SIZE % 4u) == 0u,
               "EVENT_QUEUE_DEFAULT_SIZE must be a multiple of 4");

/*----------------------------------------------------------------------------
 * Queue handle. The application declares one per queue and passes it to
 * x_event_queue_create(); it does not initialise or modify the members itself.
 * ALL members are module state -- read-only to callers.
 *
 * The counters are the synchronization core: monotonic, free-running,
 * never reset while the queue lives. The written/put pair is stored only by
 * the producer side, the read/got pair only by the consumer side; each side
 * only ever READS the other's. Unsigned wrap at 2^32 is harmless -- deltas
 * stay correct because the true difference never exceeds the buffer size.
 *--------------------------------------------------------------------------*/

typedef struct
{
    uint32_t                u32_magic;          /* Init guard */
    uint8_t                *pu8_buffer;         /* Ring storage */
    uint32_t                u32_size;           /* Ring size, bytes */

    volatile uint32_t       u32_bytes_written;  /* Producer-owned counters */
    volatile uint32_t       u32_records_put;
    volatile uint32_t       u32_records_dropped; /* Puts refused for space */
    uint32_t                u32_wr_idx;         /* Producer-private ring index */

    volatile uint32_t       u32_bytes_read;     /* Consumer-owned counters */
    volatile uint32_t       u32_records_got;
    uint32_t                u32_dropped_ack;    /* Drops the consumer has seen */
    uint32_t                u32_puts_ack;       /* Puts the consumer has seen  */
    uint32_t                u32_rd_idx;         /* Consumer-private ring index */

    pfn_event_queue_lock_t  pfn_lock;           /* Producer serialization */
    pfn_event_queue_lock_t  pfn_unlock;
    uint8_t                 u8_owns_buffer;     /* Set: destroy must free() */
}
event_queue_handle_t;

/*=============================================================================
 * Public API
 *===========================================================================*/

/* Queue lifecycle. px_config may be NULL for an all-defaults queue. A size
 * that is not a multiple of 4 is rounded DOWN and reported with
 * EQ_STATUS_SIZE_ROUNDED (the queue is live; the handle's u32_size holds the
 * net size); EQ_ERROR_SIZE only when the net size falls below
 * EVENT_QUEUE_SIZE_MIN. Creating over a handle that is already live is
 * refused (EQ_ERROR_PARAMETER) -- destroy it first. A handle in fresh
 * (zeroed) storage is always accepted; only stack garbage that happens to
 * equal the internal magic could be mistaken for a live queue, so give
 * handles static or zeroed storage. */
extern event_queue_status_t x_event_queue_create (event_queue_handle_t *px_handle,
                                                  const event_queue_config_t *px_config);
extern event_queue_status_t x_event_queue_destroy(event_queue_handle_t *px_handle);

/* Push one record. ISR-safe per the thread-safety contract above. pv_data may
 * be NULL only when u16_data_size is 0. Fails whole -- on EQ_ERROR_FULL
 * nothing was written. */
extern event_queue_status_t x_event_queue_put(event_queue_handle_t *px_handle,
                                              uint16_t u16_id,
                                              uint16_t u16_data_size,
                                              const void *pv_data);

/* Pop the oldest record into *px_record. EQ_STATUS_EMPTY when there is none.
 * Copies at most u16_buf_size payload bytes; a larger payload is truncated,
 * the overflow discarded, and EQ_STATUS_TRUNCATED returned. u16_data_size is
 * always set to the TRUE stored size. */
extern event_queue_status_t x_event_queue_get(event_queue_handle_t *px_handle,
                                              event_queue_record_t *px_record);

/* As x_event_queue_get, but non-consumptive: the record stays queued and the
 * next get (or peek) sees it again. A truncated peek discards nothing -- a
 * later get with a big enough buffer still retrieves the whole payload.
 * Consumer-context only, like get. */
extern event_queue_status_t x_event_queue_peek(event_queue_handle_t *px_handle,
                                               event_queue_record_t *px_record);

/* Discard every queued record. Consumer-context only: it drains through the
 * same path as get, so the SPSC contract is untouched and a producer may keep
 * putting concurrently (records committed after the flush passes them are
 * kept). Returns EQ_OK once the queue is empty -- flushing an already-empty
 * queue is success, not an error. */
extern event_queue_status_t x_event_queue_flush(event_queue_handle_t *px_handle);

/* Helpers. All tolerate NULL/uninitialised handles (empty / zero results).
 * is_empty and count are exact from the consumer context; free_space is exact
 * from the producer context -- from other contexts each is a snapshot that may
 * be conservatively stale. */
extern bool     b_event_queue_is_empty  (const event_queue_handle_t *px_handle);
extern uint16_t u16_event_queue_count   (const event_queue_handle_t *px_handle);

/* Payload bytes available to the next put: a put with u16_data_size up to
 * this value is guaranteed to succeed (record overhead already deducted). */
extern uint32_t u32_event_queue_free_space(const event_queue_handle_t *px_handle);

/*----------------------------------------------------------------------------
 * Dropped-event accounting.
 *
 * A put refused for want of space (EQ_ERROR_FULL) increments an internal
 * counter, so a producer that cannot stop to handle the error -- an ISR,
 * typically -- can simply ignore the return value and let the consumer find
 * out later how many events were lost. ONLY EQ_ERROR_FULL is counted: a
 * parameter or not-initialised return is a caller bug, not a dropped event.
 *
 * u32_event_queue_dropped() returns the number of drops since the last reset.
 * v_event_queue_dropped_reset() zeroes that figure.
 *
 * These follow the same single-writer discipline as everything else here: the
 * producer only ever increments its own monotonic total, the reset only ever
 * writes a consumer-owned acknowledgement of it, and the accessor subtracts
 * the two. So no read-modify-write is ever shared between contexts, and no
 * lock or interrupt masking is needed on either side -- which matters because
 * a naive "increment in put, zero in reset" would let the producer's writeback
 * silently clobber the reset on a core with no atomic RMW.
 *
 * Call the reset from the consumer context, as with get/peek/flush.
 *--------------------------------------------------------------------------*/
extern uint32_t u32_event_queue_dropped     (const event_queue_handle_t *px_handle);
extern void     v_event_queue_dropped_reset (event_queue_handle_t *px_handle);

/*----------------------------------------------------------------------------
 * Successful-put accounting -- the companion to the drop count.
 *
 * u32_event_queue_puts() returns how many records have been queued since the
 * last reset. It is a lifetime total, NOT a queue depth: a get does not
 * decrement it. Use u16_event_queue_count() for how many records are waiting.
 * Together with u32_event_queue_dropped() it gives the full picture of what a
 * producer offered -- puts + drops is every put attempt made.
 *
 * Diagnostic only; nothing in the module depends on it.
 *
 * The same single-writer split as the drop count, for the same reason plus one
 * more: the underlying total also feeds u16_event_queue_count(), so zeroing it
 * would make that subtraction underflow and report a nonsense queue depth. The
 * reset moves a consumer-owned acknowledgement instead, leaving the producer's
 * total monotonic and untouched.
 *
 * Call the reset from the consumer context, as with get/peek/flush.
 *--------------------------------------------------------------------------*/
extern uint32_t u32_event_queue_puts      (const event_queue_handle_t *px_handle);
extern void     v_event_queue_puts_reset  (event_queue_handle_t *px_handle);

#endif /* EVENT_QUEUE_H */
